### ISSUE TITLE
Upgrade to PMD 5.5

### ISSUE THREAD

**Issue by thvd** [SonarQubeCommunity/sonar-pmd#28]
Since PMD 5.5 has support for Salesforce Apex, I want to know if I could run this plugin with PMD 5.5 support?

**Comment by timwebster9** [comment]
Hi - the latest version of the plugin only supports PMD v5.4.2.  Upgrading it to 5.5 is next on my list.  I haven't looked at the Salesforce rules, but if they are standard Java PMD rules there shouldn't be a problem supporting them...

**Comment by timwebster9** [comment]
I've just had a look at this - Apex is a different language.  I only intend to support Java rules in this plugin, so I'm afraid it won't be able to support it.

It might be possible to support other languages with this plugin since it doesn't actually use the SonarQube Java analyser, but I'm not sure how it would work with the quality profiles (i.e. SonarQube doesn't offer Apex as a language).

Ideas / pull requests welcome though..:-)
